### ISSUE TITLE
Add `workingDirectory`

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/pages-action#1]
This'll help folks with monorepos or more non-standard project structures.

**Comment by jylin** [comment]
Ideally it would be "working-directory" to match the parameter naming convention used by most other github actions: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun

**Comment by aaronadamsCA** [comment]
This seems to be blocking us from using Cloudflare Pages with Functions.

As far as I can tell, Wrangler looks in `$PWD` to see if there are any functions that need to be uploaded. Since I can't change the working directory when running this action, I can't get Wrangler to pick up the functions.

I know there are workarounds, but they're a bit unwieldy.

**Comment by aaronadamsCA** [comment]
Just wanted to politely note that I filed #50 3 weeks ago that should close this issue. It would be great if somebody could review it.

**Comment by WalshyDev** [comment]
I've not had a chance to look yet @aaronadamsCA, I will next week if no one does before me.
