### ISSUE TITLE
No way to define if production or preview env

### ISSUE THREAD

**Issue by giladv** [cloudflare/pages-action#63]
Hey,

So want to use CF pages on a monorepo which the new ``workingDirectory`` feature was designed for.
Problem is, to use with monorepos, project has to be defined as a "direct upload" project which doesn't has a production branch setting in it. The only way to do it is to allow this action to have a ``productionBranch`` setting which is missing.

Please advise.

**Comment by raiyansarker** [comment]
I am having the same issue. Every push or pr in any branch results in production deployment.

**Comment by ari-becker** [comment]
I had the same issue, the workaround is to invoke the API directly to patch the `production_branch` field to be the real production branch: https://developers.cloudflare.com/api/operations/pages-project-update-project

**Comment by aaronadamsCA** [comment]
`workingDirectory` support was only released yesterday, so you should probably try again and see if you're still having this problem.

That said, the production branch name comes from the Cloudflare API, but I'm not sure the value can be changed from `main`. I believe that is a dashboard gap, since that value should still be configurable for direct uploads.

**Comment by lostpebble** [comment]
Would be amazing if there was more documentation about this!

**Comment by lostpebble** [comment]
![image](https://user-images.githubusercontent.com/1508863/225931962-4393d70c-aca1-4d93-ad9b-fe08b4aaf83e.png)

Still is set as preview... This DX is really not so great. Now I have to guess what the actual "production" branch is- probably "main". I can't set this anywhere because the page project is a "direct upload" one, because we are using Github Actions.

The idea of a single "production" branch doesn't really work in a lot of cases either.

**Comment by WalshyDev** [comment]
It'll either be "main" or "production" probably

> The idea of a single "production" branch doesn't really work in a lot of cases either.

You have to remember we use to have only Git, not Direct Uploads. Specifying a `--production` is the same as a `--branch=<prod-branch>`

We could technically add an option to just do that but not sure I like that personally (feel free to put up an issue on the Wrangler docs though)

**Comment by lostpebble** [comment]
We've managed to win with "main". Its just a lil weird because we don't even have a "main" branch (still using "master" on this repo). So overall, just opening the door for confusing.

I understand that Git was how things originally worked- but surely when it comes to direct uploads, sometimes these won't even be coming from a git repo- an option just just say `--production` seems like a no-brainer to me. Should have been there from the get-go.

**Comment by aaronadamsCA** [comment]
@WalshyDev I think the CF dash should be updated to let folks change the production branch when the project is set to manual upload. Right now it basically hard-codes to `main`, which is not always going to be correct.

IMHO the rest of the functionality is fine here and the only real problem is in the CF dash.

**Comment by nickdandakis** [comment]
For anyone else that's bumping into this and wants a quick overview on how to fix up their project's production branch as of right now...

There's two steps required here:
1. Ensure `branch: YOUR_PRODUCTION_BRANCH_HERE` is set in your Action's yaml file
2. Update your Cloudflare Pages project's `production_branch`. Here's a helpful cURL (h/t @ari-becker)
```
curl --request PATCH \
  --url https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT_IDENTIFIER_HERE/pages/projects/YOUR_PROJECT_IDENTIFIER_HERE \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Bearer YOUR_API_TOKEN_HERE' \
  --data '{ "production_branch": "YOUR_PRODUCTION_BRANCH_HERE" }'
```

Replace `YOUR_ACCOUNT_IDENTIFIER_HERE`, `YOUR_PROJECT_IDENTIFIER_HERE`, `YOUR_API_TOKEN_HERE` with your own. All of which can be found or created in your Cloudflare dashboard. Note that `YOUR_API_TOKEN_HERE` needs the `Cloudflare Pages:Edit` permission.

Replace `PRODUCTION_BRANCH_HERE` with your repo's branch (e.g. for me it's `trunk`). This should match the `branch: PRODUCTION_BRANCH_HERE` set in your Action yaml.

🚀

**Comment by Keavon** [comment]
## Hints for the above:

`YOUR_ACCOUNT_IDENTIFIER_HERE`
1. Go to your dashboard, copy the hash from the URL immediately after the hostname

`YOUR_PROJECT_IDENTIFIER_HERE`
1. Use the name of your CF Pages site as it appears in the dashboard

`YOUR_API_TOKEN_HERE`
1. Go to https://dash.cloudflare.com/profile/api-tokens
2. Click "Create Token"
3. At the bottom under "Custom token" beside "Create Custom Token" click "Get Started"
4. Give the token a name, it doesn't matter what
5. Under "Permissions", select "Account" from the first dropdown, "Cloudflare Pages" from the second, and "Edit" from the third
6. Leave the rest blank and click "Continue to summary" then "Create token"
7. Click "Copy"

`YOUR_PRODUCTION_BRANCH_HERE`
1. Probably `master` or whatever your actual Git production branch is named instead of the default of `main` which has no UI to be changed

After making those 4 changes, copy and paste it into a Linux terminal. It might be easier/more reliable to remove the `\` after each line and make it all one line. Even after doing that, I still couldn't use cmd.exe on Windows so I use to use Bash through WSL.
